SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE ROLE common;
ALTER ROLE common WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md5f0916fb62ad7f1acdcd1c264608dfe6b' VALID UNTIL 'infinity';
CREATE ROLE g_ro_public;
ALTER ROLE g_ro_public WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
CREATE ROLE g_rw_public;
ALTER ROLE g_rw_public WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';

GRANT g_rw_public TO common GRANTED BY postgres;


CREATE ROLE rmm;
ALTER ROLE rmm WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md5168f3490345f870ecb4dbbeaaa6d22d8' VALID UNTIL 'infinity';
CREATE ROLE g_rmm;
ALTER ROLE g_rmm WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
CREATE ROLE g_ota;
ALTER ROLE g_ota WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';
CREATE ROLE wisepaas;
ALTER ROLE wisepaas WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS VALID UNTIL 'infinity';

GRANT g_rmm TO rmm GRANTED BY postgres;
GRANT g_ro_public TO rmm GRANTED BY postgres;
GRANT g_ota TO rmm GRANTED BY postgres;
GRANT wisepaas TO rmm GRANTED BY postgres;


CREATE DATABASE wisepaas;
ALTER DATABASE wisepaas OWNER TO wisepaas;

