---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-portal
  namespace: wise-paas
spec:
  replicas: 1
  selector:
    matchLabels:
      belong: rmm-portal
  template:
    metadata:
      labels:
        belong: rmm-portal
    spec:
      containers:
      - name: rmm-portal
        image: ecgwc/rmm-portal
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 8080
      initContainers:
      - name: init-psql-common
        image: postgres:9.6.9-alpine
        env:
        - name: PGPASSWORD
          value: common
        command:
        - sh
        - -c
        - |
          echo "Waiting CommonWorker's PostgreSQL..."
          until psql -c 'select * from public.device' -h rmm-psql-service -U common wisepaas; do
            sleep 2
          done

---
apiVersion: v1
kind: Service
metadata:
  name: rmm-portal
  namespace: wise-paas
spec:
  type: NodePort
  selector:
    belong: rmm-portal
  ports:
  - name: rmm-portal-http
    port: 8080
    nodePort: 30333
    targetPort: 8080
    protocol: TCP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rmm-portal
  namespace: wise-paas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rmm-portal
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

