---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmm-rabbitmq
  namespace: wise-paas
spec:
  replicas: 1
  selector:
    matchLabels:
      belong: rmm-rabbitmq
  template:
    metadata:
      labels:
        belong: rmm-rabbitmq
    spec:
      containers:
      - name: rmm-rabbitmq
        image: ecgwc/rabbitmq
        ports:
        - containerPort: 1883
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 25672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: "05155853"

---
apiVersion: v1
kind: Service
metadata:
  name: rmm-rmq-service
  namespace: wise-paas
spec:
  type: NodePort
  selector:
    belong: rmm-rabbitmq
  ports:
  - name: mqtt
    port: 1883
    nodePort: 30555
    targetPort: 1883
    protocol: TCP
  - name: epmd
    port: 4369
    targetPort: 4369
    protocol: TCP
  - name: amqp
    port: 5672
    nodePort: 30777
    targetPort: 5672
    protocol: TCP
  - name: rabbitmq-portal
    port: 15672
    nodePort: 30672
    targetPort: 15672
    protocol: TCP
  - name: ctl
    port: 25672
    targetPort: 25672
    protocol: TCP

